Add peers persistence
vacp2p/mvds pull request #64
Opened 2019-08-08 08:09 UTC by adambabik

This PR adds a persistency for peers using sqlite.

Relates to #63.

_I plan to create multiple PRs for #63._

2019-08-08 08:11 UTC, decanus requested changes
@adambabik do we want things like go migrate in the makefile? I believe console client had it

2019-08-08 08:18 UTC, adambabik commented
@decanus yeah, it generates a Go file with embedded SQL migrations specific to mvds from `.sql` files. Without migrations being in a Go file, it's harder to share them and run tests as you need to deal with loading plain text files instead of using Go functions.

status-protocol-go or the console client will apply migrations defined here by importing a mvds package.

2019-08-08 08:33 UTC, decanus commented
@adambabik can you add it to the makefile?

2019-08-08 10:52 UTC, adambabik commented on Makefile
> +generate:
@decanus it's added here.

2019-08-12 06:31 UTC, cammellos approved these changes

2019-08-12 06:31 UTC, cammellos commented on persistenceutil/sqlite.go
> +const defaultKdfIterationsNumber = 64000 // nolint: deadcode,varcheck,unused
Not used?

2019-08-12 06:48 UTC, cammellos commented on peers/migrations/sqlite/1565249278_initial_schema.up.sql
> +CREATE TABLE mvds_peers (
Could you also create an index for the usage? (`group_id`, `peer_id`)

2019-08-12 09:38 UTC, adambabik commented on peers/migrations/sqlite/1565249278_initial_schema.up.sql
> +CREATE TABLE mvds_peers (
Actually there is a primary key created from these two columns. Do we need another index?

2019-08-12 09:58 UTC, decanus commented on peers/migrations/sqlite/1565249278_initial_schema.up.sql
> +CREATE TABLE mvds_peers (
Might make sense to do a UNIQUE(group_id, peer_id)

2019-08-12 10:12 UTC, cammellos commented on peers/migrations/sqlite/1565249278_initial_schema.up.sql
> +CREATE TABLE mvds_peers (
that's covered by the primary key, regarding the primary key and index usage https://github.com/vacp2p/mvds/pull/65#discussion_r312853747 , I think in this case it's all covered:
`PRIMARY KEY  (group_id, peer_id)`
should cover:

`WHERE group_id = ? and peer_id = ?`
`WHERE peer_id = ? and group_id = ?`
`WHERE group_id = ?`

but not
`WHERE peer_id = ?`

which I don't believe we are using, so it should be enough

2019-08-12 11:00 UTC, adambabik commented on peers/migrations/sqlite/1565249278_initial_schema.up.sql
> +CREATE TABLE mvds_peers (
This is also fine, we have `PRIMARY KEY (group_id, peer_id)` and the usage is:
* `WHERE group_id = ? AND peer_id = ?`
* `WHERE group_id = ?`

2019-08-12 11:00 UTC, adambabik commented
@decanus can you please take a look again?

2019-08-21 10:20 UTC, adambabik commented
Closed by #68

2019-08-21 10:20 UTC, closed without merging