Add SyncState persistency
vacp2p/mvds pull request #65
Opened 2019-08-09 09:54 UTC by adambabik

This PR adds a persistency for peers using sqlite.

Relates to #63.

_This branch is created from a PR #64._

2019-08-12 06:40 UTC, cammellos requested changes
looks good, the only thing I think it's def worth changing is the iteration in `Map` so we only hit the right records, as it might impact performance as more messages are sent

2019-08-12 06:40 UTC, cammellos commented on state/state_sqlite.go
> +		return errors.New("state not found")
Are we sure we want to return an error when the state is not there? feels more like a warning (returning 0, and handled on the caller if necessary). If we do decide to return an error (I am fine with it), then it's worth having `ErrStateNotFound` or something so we can handle it on the caller, what do you reckon?

2019-08-12 06:40 UTC, cammellos commented on state/migrations/sqlite/1565341329_initial_schema.up.sql
> +CREATE TABLE mvds_states (
Would you mind creating as well some indexes based on current usage ? (`peer_id`, `message_id`, `send_epoch`)

2019-08-12 06:40 UTC, cammellos commented on state/state_sqlite.go
> +	states, err := p.All()
I would query for only those states that have `SendEpoch` > `epoch` (we can index the field), otherwise we end up iterating over an ever growing collection

2019-08-12 09:32 UTC, adambabik commented on state/state_sqlite.go
> +		return errors.New("state not found")
Totally. I missed it here but it should be an exported `error` instance.

2019-08-12 09:44 UTC, adambabik commented on state/migrations/sqlite/1565341329_initial_schema.up.sql
> +CREATE TABLE mvds_states (
There is a primary key on `(peer_id, message_id)` so only `send_epoch` is not indexed. Similar question to the other comment whether we need another index on the columns which has a primary key? If it's unknown, I will verify what's faster.

2019-08-12 10:04 UTC, adambabik commented on state/state_sqlite.go
> +	states, err := p.All()
To clarify, in this case, if `state.SendEpoch > epoch` we skip the state from processing. 
```
		if state.SendEpoch > epoch {
			continue
		}
```

So, we need to query only these states that has `SendEpoch <= epoch` which might result in a lot of states anyway unless they are properly removed.

Question is whether there should be any states that have `SendEpoch < epoch`? From the code, it looks like the answer is it's possible because if we fail to send messages at a turn of the loop, the epoch is incremented and messages stay.

2019-08-12 10:05 UTC, cammellos commented on state/migrations/sqlite/1565341329_initial_schema.up.sql
> +CREATE TABLE mvds_states (
a primary key on peer_id and message_id will cover queries such as:
WHERE peer_id = ?
where peer_id =? AND message_id = ?
where message_id = ? and peer_id = ?

but not:

WHERE message_id = ? 

order is left -> right

if you swap the constraint:
(message_id, peer_id)

it will cover:

`message_id = ?`
but not 
`peer_id = ?`

(combined it will be covered, regardless of the order, as the query optimizer will understand to sort them)

2019-08-12 10:09 UTC, cammellos commented on state/state_sqlite.go
> +	states, err := p.All()
yes, sorry, I got it the other way around. 
I would still query with `<=` (and not `=`), just to make sure, but you raise a good point, I guess we need to make sure stuff does not accumulate, but probably best left for a separate PR.

2019-08-12 10:21 UTC, adambabik commented on state/migrations/sqlite/1565341329_initial_schema.up.sql
> +CREATE TABLE mvds_states (
Sorry, I typed it from memory. We actually have it in the "right" order (the reverse one would work as well due to our usage). We have `PRIMARY KEY (message_id, peer_id)` and the usage is `WHERE message_id = ? AND peer_id = ?` twice and `WHERE send_epoch <= epoch` so we will be golden if just add an index on `send_epoch` column.

2019-08-12 19:11 UTC, adambabik commented
@cammellos applied changes in https://github.com/vacp2p/mvds/pull/65/commits/7244521f6d8955a49dbdb543e08d3d7fa262dbc2.

2019-08-12 19:38 UTC, cammellos approved these changes

2019-08-21 10:20 UTC, adambabik commented
Closed by #68

2019-08-21 10:20 UTC, closed without merging