feature/mdf
vacp2p/mvds pull request #76
Opened 2019-10-22 12:50 UTC by decanus

Implements [mdf](https://specs.vac.dev/mdf)

2019-10-29 19:39 UTC, decanus commented
@adambabik & @cammellos it might be good to get your review on this code already before I go ahead and finalize

2019-10-29 19:52 UTC, decanus commented
![image](https://user-images.githubusercontent.com/7621705/67803761-fccae980-fa8d-11e9-8106-2822872edb55.png) 
parents works and are automatically added. the printed hash is the id of the first message that was added to the second message.

2019-10-29 21:12 UTC, adambabik commented on node/node.go
> +	EVENTUAL ResolutionMode = iota
Usually, it's a good practice to start from `1` so `iota + 1`. Starting with `iota` makes `a := EVENTUAL` indistinguishable from `var a ResolutionMode`.

Also consts in Go are just capitalized:
```suggestion
	EventualMode ResolutionMode = iota + 1
```

2019-10-29 21:12 UTC, adambabik commented on node/node.go
> +	CONSISTENT
```suggestion
	ConsistentMode
```

2019-10-29 21:12 UTC, adambabik commented on node/node.go
> +	parents := make([][]byte, 0)
You can move it after `p, err := ...` and do
```go
parents := make([][]byte, len(p))
```
to avoid slice resizing.

Remember that then you need to use `parents[idx] = id[:]`.

2019-10-29 21:12 UTC, adambabik commented on node/node.go
> +	err := n.store.Add(&m)
Any reason `m` is passed by pointer here and by value in `err = n.broadcastToGroup(groupID, n.ID, m)`?

2019-10-29 21:12 UTC, adambabik commented on node/node.go
> +	toRemove := make([]state.State, 0)
```suggestion
	var toRemove []state.State
```
is more idiomatic and won't allocate memory if not used.

2019-10-29 21:12 UTC, adambabik commented on node/node.go
> +			has, _ := n.store.Has(pid); if has {
```suggestion
			if has, _ := n.store.Has(pid); has {
```

2019-10-29 21:12 UTC, adambabik commented on store/messagestore_sqlite.go
> +		vals := make([]interface{}, 0)
```suggestion
		vals := make([]interface{}, len(message.Metadata.Parents) * 2)
```

2019-10-29 21:12 UTC, adambabik commented on store/messagestore_sqlite.go
> +			query += "(?, ?),"
As `Parents` is `O(n)`, I would encourage to use string builder https://www.calhoun.io/concatenating-and-building-strings-in-go/. Otherwise, it might result in `N` string allocations and put a pressure on GC.

2019-10-29 21:12 UTC, adambabik commented on store/messagestore_sqlite.go
> +		if err != nil {
`_ = tx.Rollback()` is missing.

2019-10-29 21:12 UTC, adambabik commented on store/messagestore_sqlite.go
> +	message.Metadata = &protobuf.Metadata{Ephemeral: false, Parents: make([][]byte, 0)}
```suggestion
	message.Metadata = &protobuf.Metadata{Ephemeral: false}
```
is the same but does not allocate memory for `Parents` by default. Go can handle `append` on `nil`.

2019-10-29 21:12 UTC, adambabik commented on store/messagestore_sqlite.go
> +	defer rows.Close()
Can be moved right after `err` check for readability.

2019-10-29 21:12 UTC, adambabik commented on store/messagestore_sqlite.go
> +	defer rows.Close()
Similar remark as in the previous comment.

2019-10-29 21:12 UTC, adambabik commented on store/messagestore_sqlite.go
> +	result := make([]state.MessageID, 0)
```suggestion
	var result []state.MessageID
```

2019-10-29 21:12 UTC, adambabik commented
BTW https://specs.vac.dev/mdf is awesome. Helped me a lot understand what this PR is about.

2019-10-29 23:46 UTC, decanus commented on store/messagestore_sqlite.go
> +		vals := make([]interface{}, 0)
@adambabik I find that to make the logic a little more annoying

2019-10-30 07:10 UTC, adambabik commented on store/messagestore_sqlite.go
> +		vals := make([]interface{}, 0)
It's more efficient but here it does not matter. Alternatively you can go with 
```suggestion
		var vals []interface{}
```
which is equivalent of what you wrote (minus mem allocation in case no appends) and idiomatic way of declaring a slice.

2019-10-30 08:41 UTC, oskarth commented on dependency/dependency_memory.go
> +type memoryDependency struct {
Can we add some doc string here?

2019-10-30 08:42 UTC, oskarth commented on node/node.go
> +const (
Needs doc string / comments, perhaps with ref to spec. Not clear what this does

2019-10-30 08:42 UTC, oskarth commented on node/node.go
> +	p, err := n.store.GetMessagesWithoutChildren(groupID)
Why are we getting messages without children?

2019-10-30 08:43 UTC, oskarth commented on node/node.go
> +	err = n.broadcastToGroup(groupID, n.ID, m)
Is this broadcast behaviour documented in spec?

2019-10-30 08:44 UTC, oskarth commented on node/node.go
> +func (n *Node) resolve(sender state.PeerID, msg *protobuf.Message) {
docstring/comment on what this function and why it is there

2019-10-30 08:45 UTC, oskarth reviewed
left some comments in-line

2019-10-30 08:47 UTC, cammellos commented on node/node.go
> +	p, err := n.store.GetMessagesWithoutChildren(groupID)
That's the definition of a parent, a parent of a new message is any message without a children, maybe worth renaming the functions to `GetParents` or something

2019-10-30 08:51 UTC, oskarth commented on node/node.go
> +	p, err := n.store.GetMessagesWithoutChildren(groupID)
yeah, my point is that the the naming is confusing

2019-10-30 08:52 UTC, cammellos commented on node/node.go
> +func (n *Node) resolve(sender state.PeerID, msg *protobuf.Message) {
This approach is probably not scaling very well, it does not have to be performant from the get go, but before further optimization  we need to re-think the strategy

2019-10-30 08:56 UTC, oskarth commented on node/node.go
> +	p, err := n.store.GetMessagesWithoutChildren(groupID)
I also noticed we don't define children here https://specs.vac.dev/mdf.html

2019-10-30 11:37 UTC, decanus commented on dependency/dependency_memory.go
> +type memoryDependency struct {
@oskarth will do once we actually use.

2019-10-30 12:10 UTC, decanus commented on node/node.go
> +	err = n.broadcastToGroup(groupID, n.ID, m)
@oskarth yes and no. I called it broadcast but its really just the basic sending logic that was there before semi documented in the [`flow`](https://specs.vac.dev/mvds.html#flow) part of the spec. This doesn't include anything on who a message should be sent to within a group however.

2019-10-30 12:18 UTC, decanus commented on node/node.go
> +func (n *Node) resolve(sender state.PeerID, msg *protobuf.Message) {
@oskarth @cammellos this function needs more love and needs to be thought about a bit further. Once I have that I will clean it up and make it more understandable.

2019-10-31 14:43 UTC, decanus commented on node/node.go
> +func (n *Node) resolve(sender state.PeerID, msg *protobuf.Message) {
@oskarth and @cammellos I reworked the functions a bit, would be good for you to have another look. @cammellos as for any discussions we had on status lets keep them here for longevity.

2019-10-31 15:01 UTC, cammellos commented on node/node.go
> +func (n *Node) resolve(sender state.PeerID, msg *protobuf.Message) {
Cool, basically we had a chat about how to handle parents dependencies, just throwing some ideas, these is what I am wondering:

Pulling dependency chain from the db is a bit fiddle and pulling them one by one won't scale likely (a message has `n` parents, each of those messages can have `m` parents). This is something that sql dbs don't do very well. An embedded graph db is more suited for these kind of queries, so that's an option although fairly heavy handed.

Another option is to have clients specify dependencies (including ancestors) using a bloom filter, which is to be included in the payload. The bloom filter is capped to a reasonable amount of ancestors (say 512 for example), and based on that we can select the size of the bloom filter.

This means that with a single query (if the db allows bloom filter queries, which some do) I can pull all the dependencies that I have for a given message, at that point I can traverse the tree in memory and check if satisfied). As long as the method for capping the dependencies is stable (i.e any client will come up with the same 512 message dependencies given a message), seems like it should be working. The bandwidth cost of a bloom filter is likely negligible.

2019-10-31 17:53 UTC, decanus commented on node/node.go
> +func (n *Node) resolve(sender state.PeerID, msg *protobuf.Message) {
@cammellos so codewise I am currently trying to figure out how to state that our nodes sync dependencies to `n` depth.

2019-10-31 18:18 UTC, cammellos commented on node/node.go
> +func (n *Node) resolve(sender state.PeerID, msg *protobuf.Message) {
I don't think we can use depth (or at least depth only) as the number of dependencies in a single level is potentially unbound, where `N` is the number of members in the conversation, so I would rather cap to a concrete number (configurable) and offer a deterministic way to order them so everyone in the group is on the same page on which are the dependencies (say you sort them by level, and within a level you sort them by timestamp/message id, so that if client A and B receive a message, and they both cap dependencies to 512, they will pick the same deps, not that they have to , one might use 512 and the other 1024).

A recursive function is the most natural way to model this instinctively, or you can parallelize by following branches, although a bit trickier

2019-11-01 14:45 UTC, decanus commented
@cammellos @oskarth The basics of the spec are implemented and what we need for dasy is essentially done. The part I am not happy with is the casual consistency, my proposal is to merge this pr and create an issue describing how to change the consistent dependency resolution code and do this in a separate pr.

2019-11-01 15:07 UTC, cammellos requested changes
Looks good to me, I would just add some tests exercising those functions, as if anyone else is to modify them, it won't be able to validate against it

2019-11-01 15:07 UTC, cammellos commented on node/node.go
> +	InteractiveMode Mode = iota
Same as previous suggestion from @adambabik , `iota + 1` ?

2019-11-01 15:07 UTC, cammellos commented on node/node.go
> +	p, err := n.store.GetMessagesWithoutChildren(groupID)
Should we rename this then? @decanus

2019-11-01 15:07 UTC, cammellos commented on node/node.go
> +func (n *Node) resolveConsistently(sender state.PeerID, msg *protobuf.Message) {
It would be good to cover this path with a test, although implementation might change, it will help us validating the behavior is correct, otherwise is left to whoever will modify it.

2019-11-01 15:07 UTC, cammellos commented on store/messagestore_dummy.go
> +func (ds *DummyStore) GetMessagesWithoutChildren(group state.GroupID) ([]state.MessageID, error) {
Some tests covering this would be handy

2019-11-02 15:15 UTC, adambabik reviewed
Which bindata lib do you use? It would be nice to pin a version on Makefile so that everyone uses the same.

2019-11-02 15:15 UTC, adambabik commented on dependency/dependency.go
> +type MessageDependency interface {
Suggestion to simplify naming:
```go
type Tracker interface {
    Add(msgID, dep state.MessageID) error
    Dependants(msgID state.MessageID) ([]state.MessageID, error)
    Resolve(msgID, dep state.MessageID)
    ContainsUnresolved(msgID state.MessageID) (bool, error)
}
```

then when it's imported: `dependencies dependency.Tracker` and `dependency.NewInMemoryTracker`.

2019-11-02 15:15 UTC, adambabik commented on dependency/dependency_memory.go
> +	for i, val := range md.dependents[dependency] {
You can do this because you stop iterating immediately when an item is found.

```suggestion
	for _, item := range md.dependents[dependency] {
		if item != msg {
		    continue
		}
         	md.dependents[dependency] = remove(md.dependents[dependency], id)
		md.dependencies[msg] -= 1
		return nil
	}
	return nil
```

2019-11-02 15:15 UTC, adambabik commented on dependency/dependency_sqlite.go
> +	_, err := sd.db.Exec(`INSERT INTO mvds_dependencies (msg, dependency) VALUES (?, ?)`, msg[:], dependency[:])
```suggestion
	_, err := sd.db.Exec(`INSERT INTO mvds_dependencies (msg_id, dependency) VALUES (?, ?)`, msg_id[:], dependency[:])
```

Generally, I see `msg` in many places while we actually deal with `msgID`. For me it's confusing because I need to check whether it's actual message or only an ID.

2019-11-02 15:15 UTC, adambabik commented on dependency/dependency_sqlite.go
> +
```suggestion
```

2019-11-02 15:15 UTC, adambabik commented on dependency/dependency_sqlite.go
> +	msgs := make([]state.MessageID, 0)
```suggestion
	var msgs []state.MessageID
```

the same result but no memory allocated if no data in DB.

2019-11-02 15:15 UTC, adambabik commented on dependency/dependency_sqlite.go
> +	if _, err := result.RowsAffected(); err != nil {
What is this for?

2019-11-02 15:15 UTC, adambabik commented on dependency/migrations/sqlite/1572614870_initial_schema.up.sql
> +    dependency BLOB NOT NULL
Index on this one could be helpful for `SELECT msg FROM mvds_dependencies WHERE dependency = ?` and deleting.

2019-11-03 00:50 UTC, decanus commented
@adambabik 

```
go-bindata 3.1.0 (Go runtime go1.12.5).
Copyright (c) 2010-2013, Jim Teeuwen.
```

https://github.com/jteeuwen/go-bindata

2019-11-03 18:46 UTC, adambabik commented
@decanus this one is not maintained anymore. In status-protocol-go we use a different one https://github.com/status-im/status-protocol-go/blob/master/Makefile#L37.

2019-11-03 19:08 UTC, decanus commented
@adambabik updated

2019-11-04 07:16 UTC, oskarth commented on node/node.go
> +func (n *Node) resolve(sender state.PeerID, msg *protobuf.Message) {
@decanus can we capture this context in a clear GHI problem description? Then add a TODO to figure out a better strategy, so we can merge this (naive) solution for now

2019-11-04 17:12 UTC, decanus commented on store/messagestore_dummy.go
> +func (ds *DummyStore) GetMessagesWithoutChildren(group state.GroupID) ([]state.MessageID, error) {
Wrote one for the persistent version @cammellos

2019-11-04 18:42 UTC, adambabik commented on dependency/tracker.go
> +	MarkResolved(msg state.MessageID, dependency state.MessageID) error
Maybe just 
```suggestion
	Resolve(msg state.MessageID, dependency state.MessageID) error
```

2019-11-04 18:42 UTC, adambabik commented on dependency/tracker.go
> +	HasUnresolvedDependencies(id state.MessageID) (bool, error)
And maybe:
```suggestion
	IsResolved(id state.MessageID) (bool, error)
```
Unless it's not the same.

2019-11-04 18:42 UTC, adambabik commented on dependency/tracker_sqlite.go
> +	if _, err := result.RowsAffected(); err != nil {
Still not sure why we need call `RowsAffected`.

2019-11-04 18:42 UTC, adambabik commented on store/messagestore_sqlite.go
> +		err := rows.Scan(&parent)
I am not sure about this one. I don't exactly know how Scan works but such a scenario is likely:
1. First row has a parent of 10 bytes,
2. It's read into `parent` variable,
3. Next row has a parent with 5 bytes,
4. It's read into `parent` but can we be sure it was cleaned? 

I would put `parent` inside `for` loop.

2019-11-04 18:42 UTC, adambabik commented on store/messagestore_sqlite.go
> +	var parent []byte
Similar case as above in `Get`.

2019-11-04 18:42 UTC, adambabik commented on store/messagestore_sqlite_test.go
> +func groupId() state.GroupID {
Nitpick: named return value would be nice here:
```go
func groupID() (id state.GroupID) {
    _, _ = rand.Read(id[:])
    return
}
```
Should do the same.

2019-11-04 18:42 UTC, adambabik commented on store/migrations/sqlite/1572372377_initial_schema.up.sql
> +    message BLOB NOT NULL,
```suggestion
    message_id BLOB NOT NULL,
```

2019-11-04 18:42 UTC, adambabik commented on store/migrations/sqlite/1572372377_initial_schema.up.sql
> +    parent  BLOB NOT NULL,
```suggestion
    parent_id  BLOB NOT NULL,
```

2019-11-04 18:42 UTC, adambabik commented on store/migrations/sqlite/1572372377_initial_schema.up.sql
> +    group_id  BLOB    NOT NULL,
Could use an index.

2019-11-04 20:51 UTC, decanus commented
@cammellos added test.

2019-11-05 05:37 UTC, oskarth commented on dependency/tracker.go
> +	Dependants(id state.MessageID) ([]state.MessageID, error)
Are or should all of these interface functions be referred to in the spec?

2019-11-05 05:37 UTC, oskarth commented on protobuf/sync.proto
> +package vac.mvds;
Do we specify version somewhere? I just realized. Or do we want this to be out of band?

2019-11-05 05:44 UTC, decanus commented on dependency/tracker.go
> +	Dependants(id state.MessageID) ([]state.MessageID, error)
@oskarth, no it's an implementation detail. Another implementation could handle this completely differently.

2019-11-05 05:45 UTC, decanus commented on protobuf/sync.proto
> +package vac.mvds;
@oskarth we probably should somewhere.

2019-11-05 09:13 UTC, cammellos commented on protobuf/sync.proto
> +package vac.mvds;
Version of the protocol? 
If so you can leave it unspecified until you have to change it or use it, it will be read as 0 by newer clients when receiving from older, and ignored by older clients when receiving from newer. But we can also add it now.

2019-11-05 09:18 UTC, cammellos approved these changes
looks good to me, I would wait for @adambabik to review the go parts before merging

2019-11-05 10:14 UTC, oskarth approved these changes
Seems OK, didn't look into the Go code in detail

2019-11-05 14:29 UTC, decanus commented on protobuf/sync.proto
> +package vac.mvds;
@cammellos I was thinking of adding a version field later to MVDS. It will be easy to tell which clients are below first version because version will be 0.

2019-11-05 15:50 UTC, adambabik approved these changes

2019-11-05 15:50 UTC, adambabik commented on dependency/tracker_sqlite.go
> +	if err != nil {
```suggestion
	return err
```

it can be replaced with a single line.

2019-11-05 16:32 UTC, merged